spring:
  datasource:
    username: 'root'
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

# 整合 MyBatis
mybatis:
  type-aliases-package: 'com.example.pojo'
